### ISSUE TITLE
Not seeing new/updated data in Flask

### ISSUE THREAD

**Issue by robinandeer** [dgilland/flask-alchy#3]
Hi,

I have a problem where data populated from a different session (CLI) doesn't show up in the server until I restart it. I initialize the `Alchy` object by passing in the `Model` and then running `init_app` in my Flask factory function.

As I understand Flask-SQLAlchemy will handle setting up and tearing down the sessions on each request. Do you have any idea of what this is? Have you seen it before?

This is my project: https://github.com/Clinical-Genomics/taboo/blob/master/taboo/server/ext.py
Database: MySQL

**Comment by dgilland** [comment]
The teardown function that Flask-SQLAlchemy registers will call `session.remove()` at the end of all requests. So each new request should have a "fresh" session.

After you use your CLI to insert/update the database and see that the data is not shown by the web server, have you queried the database directly to see whether the data is there (e.g. using mysql CLI)? It could be that your CLI is not committing the transaction.

Otherwise, the issue could be any number of things:
- Is the web page that shows the data being cached?
- What kind of configuration is used for the CLI db connection vs the web db connection? Are the engine/session options used different?
- How is the web app being deployed? Is there a WSGI server in front of it? Is it the Flask development server?
- etc.

For debugging, you could use the Flask development server and use something like `import pdb; pdb.set_trace()` within one of your route handlers to manually inspect the state of your database within the request. You could then do some dirty-debugging within that context to determine if the session is stale, if there's any way to remove/close/dispose of the session such that you can get to the data, etc.

But generally speaking when you have two "clients" reading/writing to the database and one of them can't see data committed by the other, then usually it's database transaction related where either the "writer" hasn't committed their transaction so no one else can see the changes or the "reader" is within a transaction and can't see any other transactions that committed after it started its own transaction.

**Comment by robinandeer** [comment]
Thank you for your extended answer! Really appreciate it 👍 

I continue to debug my issue. I can provide a summary:
- Data loaded via the CLI show up as expected in MySQL Workbench but not in my server
- I can see the connection time resetting for every request which I guess means that part is working
- I now noticed that I get different data depending if I use `SomeModel.query.get(model_id)` vs. `db.session.query(SomeModel).get(model_id)`

I think I'll use the global `query` for now

**Comment by jeffwidman** [comment]
> I now noticed that I get different data depending if I use `SomeModel.query.get(model_id)` vs. `db.session.query(SomeModel).get(model_id)` 

That's a little scary actually because it implies you're potentially using multiple SQLAlchemy sessions within the same Flask web request. While it can work if you're consistent on which one you use, it's asking for trouble... 

This sounds like it's not actually an issue with Flask-Alchy, but rather an issue with your app config, and probably a better fit for StackOverflow.

**Comment by dgilland** [comment]
@robinandeer, you might want to check whether:

``` python
SomeModel.query.session == db.session
SomeModel.query.session.connection() == db.session.connection()
```

The `Model.query` property is bound to the same session as the `Alchy(...).session` object assuming you passed `Alchy(..., Model=Model)` and have `SomeModel(Model)`. The session objects should be same whether you use `Model.query` or `db.session.query(Model)` so the fact that you are getting different results suggests you have two different database connections.

Since it appears you may have two different database connections, you may also be connecting to different databases. Might want to also check:

``` python
SomeModel.query.session.connection().engine
db.session.connection().engine
```

And see what databases they are connected to.

``` python
SomeModel.query.session.connection().engine.url
db.session.connection().engine.url
```

**Comment by robinandeer** [comment]
Okey, yeah that makes sense. I do make another database connection before I start the Flask server process. That seems to confuse the app. Skipping that makes both ways of querying return the same updated result!

You can close the issue but for completeness; comparing the sessions return false:

``` python
ipdb> db.session
<sqlalchemy.orm.scoping.scoped_session object at 0x1044418d0>
ipdb> SomeModel.query.session
<flask_sqlalchemy.SignallingSession object at 0x1051bec50>
```

However the connection is the same 👍 

Thanks again @dgilland and @jeffwidman!
