### ISSUE TITLE
Working with multiple databases

### ISSUE THREAD

**Issue by robinandeer** [dgilland/flask-alchy#4]
Hi,

I'm setting up Alchy because I wanna use my models both in a CLI as well as in a web server

However, I can't quite figure out how to work with Flask-SQLAlchemy "binds": http://flask-sqlalchemy.pocoo.org/2.1/binds/

Is there a way to setup Flask-Alchy with multiple "Models"?

**Comment by robinandeer** [comment]
Just so I understand; I do need to use the same base `Model` instance for all my table definitions? This might be the thing I find a bit confusing..

**Comment by dgilland** [comment]
I'm actually not a huge fan of model binds. I generally find it easier to have two (or more) model bases and database client objects (one for each separate database backend).

But essentially what binds are doing in this case are allowing you to use the same declarative model base for models that are associated with different backends while also using a single database client that is able to select which backend to communicate with based on the bind key of the model.

So basically the bind keys in `SQLALCHEMY_BINDS` (i.e. "users" and "appmeta" from the linked example) point to database URIs. Then the `__bind_key__` attribute of a model associates that model with the corresponding database that the bind URI points references. So when you do something like `db.query(User)` or `User.query`, under the hood, the correct database connection is used based on `User.__bind_key__`.

Alchy implements the same logic that Flask-SQLAlchemy has binds and Flask-Alchy extends Flask-SQLAlchemy so you get the same bind functionality in all three.

If you want to stay away from binds and just have multiple model bases and clients, then you'd do something like:

``` python
from alchy import Manager, ModelBase, make_declarative_base

class BaseModel(ModelBase):
    # extend model if needed

ModelA = make_declarative_base(BaseModel)
ModelB = make_declarative_base(BaseModel)

class TableA(ModelA):
    # define table

class TableB(ModelB):
    # define table

db_a = Manager(config, Model=ModelA)
db_b = Manager(config, Model=ModelB)

db_a.query(TableA)
TableA.query

db_b.query(TableB)
TableB.query
```

Does this help clear things up?

BTW, you don't need the multiple bind functionality, you might be interested in [sqlservice](https://github.com/dgilland/sqlservice) which is a rewrite/re-implementation of alchy.

**Comment by dgilland** [comment]
> Just so I understand; I do need to use the same base Model instance for all my table definitions? This might be the thing I find a bit confusing..

If you use bind keys, then you only need a single base model. The default when a model doesn't define `__bind_key__` is `None` which will use whatever is defined for `SQLALCHEMY_DATABASE_URI`.

There are some unit tests in alchy that show more examples of using binds: https://github.com/dgilland/alchy/blob/develop/tests/test_manager.py#L112

**Comment by robinandeer** [comment]
Hi, thank you for your answer!

I was under the impression that using binds was the only way to use multiple databases hehe
If there's a different approach I would rather use different model bases!

So your example makes a lot of sense but this is outside the context of a server/long running process. What Flask-Alchy gives me is the automated setup/teardown of the session for every request which I really want :)

However, the Flask config key `SQLALCHEMY_DATABASE_URI` seems hardcoded in Flask-SQLAlchemy... 😛  so I can't see how I can setup Flask-Alchy with two model bases, do you understand?

I will check out "sqlservice" tho!
I've been using Alchy for a while and really liking it :D
It's so great to be able to reuse my models in both the server and, in my case, in the CLI ^^

**Comment by dgilland** [comment]
Binds are the only way (out of the box) to use multiple databases with Flask-SQLAlchemy/Flask-Alchy since, as you point out, `SQLALCHEMY_DATABASE_URI` access is tied to `app.config['SQLALCHEMY_DATABASE_URI']`.

If you are only interested in the database connection management within the request/response lifecycle, it might be easier to write your own teardown function that removes the session after each request similar to: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L832. You can then reference your multiple database clients in the teardown function as needed.

Alternatively, you could modify the `init_app` method of `Flask-Alchy` to accept a config argument that could be used in place of `app.config`. In this way you could define your `app.config` with something like:

``` python
config = {
    'DATABASES': {
        'db1': {'SQLALCHEMY_DATABASE_URI': '', ...},
        'db2': {'SQLALCHEMY_DATABASE_URI': '', ...}
}
```

then have something like:

``` python
db1 = MyFlaskAlchy()
db2 = MyFlaskAlchy()

def create_app(config):
    app = Flask(config)
    db1.init_app(app, config=app.config['DATABASES']['db1'])
    db2.init_app(app, config=app.config['DATABASES']['db2'])
```

But looking back over Flask-SQLAlchemy, that approach may prove more complicated since `app.config` is used in a bunch of other places other than just `init_app`. So it may be "easier" to just create your own Flask extension that wraps an instance of `alchy.Manager` or `sqlservice.SQLClient` and handles the setup/teardown features you need.

Personally, I'd prefer to see a proxy extension defined something like this:

``` python
from flask import current_app

class FlaskSQLService(object):
    def init_app(self, app, db):
        # Store reference to database client on app instance.
        app.extensions['sqlservice'] = db

        @app.teardown_appcontext
        def shutdown_session(response_or_exc):
            self.remove()
            return response_or_exc

    @property
    def _db(self):
        return current_app.extensions['sqlservice']

    def __getattr__(self, attr):
        # Proxy attribute access to our database client instance.
        return getattr(self._db, attr)
```

where the extension is "dumb" and only handles things specific to Flask (like setup/teardown functions) but still allowing the "global" extension instance usage pattern (i.e. where another module imports the extension and uses it as needed). The database client creation is then delegated to outside the extension class:

``` python
from sqlservice import SQLClient
from mymodels import Model1, Model2
from myextensions import FlaskSQLService

db1 = FlaskSQLService()
db2 = FlaskSQLService()

def create_app(config):
    app = Flask(config)
    db1.init_app(app, SQLClient(app.config['DATABASES']['db1'], model_class=Model1)
    db2.init_app(app, SQLClient(app.config['DATABASES']['db2'], model_class=Model2)
```

**Comment by robinandeer** [comment]
This is amazing!! Thank you again :D

Yeah this is maybe the way forward - I've shied away from reimplementing the setup/teardown stuff in Flask-SQLAlchemy bc I'd prefer to "stand on their shoulders" but I guess I can give it a go
